package com.vectrune

import com.intellij.lang.ASTNode
import com.intellij.lang.ParserDefinition
import com.intellij.lang.PsiParser
import com.intellij.lexer.Lexer
import com.intellij.openapi.project.Project
import com.intellij.psi.FileViewProvider
import com.intellij.psi.PsiElement
import com.intellij.psi.PsiFile
import com.intellij.psi.tree.IFileElementType
import com.intellij.psi.tree.TokenSet
import com.vectrune.parser.RuneParser // Generated by BNF
import com.vectrune.RuneFile

class RuneParserDefinition : ParserDefinition {
    val FILE = IFileElementType(RuneLanguage)
    val WHITE_SPACES = TokenSet.create(TokenType.WHITE_SPACE)
    val COMMENTS = TokenSet.create(RuneTypes.COMMENT) // Match your BNF token name

    override fun getWhitespaceTokens(): TokenSet = WHITE_SPACES
    override fun getCommentTokens(): TokenSet = COMMENTS
    override fun getStringLiteralElements(): TokenSet = TokenSet.EMPTY

    override fun createLexer(project: Project?): Lexer = RuneLexerAdapter()
    override fun createParser(project: Project?): PsiParser = RuneParser()
    override fun getFileNodeType(): IFileElementType = FILE
    override fun getCommentTokens(): TokenSet = TokenSet.create(RuneTypes.COMMENT)
    override fun getStringLiteralElements(): TokenSet = TokenSet.EMPTY
    override fun createElement(node: ASTNode): PsiElement = RuneTypes.Factory.createElement(node)
    override fun createFile(viewProvider: FileViewProvider): PsiFile = RuneFile(viewProvider)
}